### ISSUE TITLE
Tab size doesn't update if changing other tab.

### ISSUE THREAD

**Issue by nosferatu500** [ticlo/rc-dock#107]
I am testing tab resizing using onLayoutChange.

For example: I have 2 tabs (A, B).

When I resize tab A, tab B also resizes, but inside onLayoutChange I can see that the variable "size" only changes for tab A, although 2 tabs have been visually resized.

I need to get updated sizes from all tabs and not just from the one that I change myself. How can I get it?

**Comment by rinick** [comment]
the size is used by flexbox css,  size=200 vs size=100 just mean one will take twice the space as the other.
I use the actual pixel size during dragging because that's convenient, but the size is not updated with accurate value at runtime, because measuring element size all the time is a bad practice.

if you need the size of your panels or tabs, you can simply query for them, and measure it yourself.  the id of element is the same id you put in tab data
