### ISSUE TITLE
Feature request: panel size constraint; hide/show tab list

### ISSUE THREAD

**Issue by aztack** [ticlo/rc-dock#127]
Thanks for sharing this great library! 🎉

Here are some features I and others wanted:

- Support min/max width/height for Panel: 
- Make tabs list can be `show/hide` when needed

For example, the left sidebar of VS Code is tab-less and fix-sized.
Or, is there a way/workaround to achieve this please give me a hint or example code.

Thanks!

**Comment by rinick** [comment]
min width height is available in TabData as well as panelLock
a strict max size is impossible, because it might be grouped in the same H/V box when other panel has a min size bigger than its max size, which will break the alignment of panels.

for tabless  panel,  in the panel style example, I show hide the header on mouse over, but you can just make it always hidden
https://ticlo.github.io/rc-dock/examples/#panel-style
