### ISSUE TITLE
Cannot get the reference of rc-dock to access the methods like dockMove

### ISSUE THREAD

**Issue by shubhankar1solanki** [ticlo/rc-dock#21]
I tried creating the reference of the DockLayout object and accessing it with the ref object. But I'm not able to do that. Here is the code
```
import React, { useRef } from 'react';
import DockLayout from 'rc-dock';
import './App.css';

function App() {

  const rcDockRef = useRef(null);

  const defaultLayout = {
    dockbox: {
      mode: 'horizontal',
      children: [
        {
          tabs: [
            {id: 'tab1', title: 'tab1', content: <div>Hello World</div>}
          ]
        }
      ]
    }
  };

  return (
      <DockLayout
        ref={rcDockRef}
        defaultLayout={defaultLayout}
      />
  );
}

export default App;
```

It will be great if you guys can help me out with this?
My goal is to access methods of rc-dock like `dockMove`.

**Comment by andrewsantarin** [comment]
@shubhankar1solanki You're already on the right track. You'd use `current` from the `useRef(null)` hook in a function (or `createRef()` in a class) to retrieve the `<DockLayout>` instance API.

```js
const rcDockRef = useRef(null);
rcDockRef.current.dockMove(/* your params */);
```
But you can't use it directly like this!

You'd get an error if you did exactly that because you're trying to get component API before its initial render (mount lifecycle). At this point, the API stored in `current` is `null`, even though the reference is ready. You need to wait until the component has been mounted, **then** you can get your API. In TypeScript, it reads `current: DockLayout | null` instead of `current: DockLayout`. You'll have to type guard it yourself.

Check this sandbox:
https://codesandbox.io/s/hopeful-stallman-u1802

Mind you: this actually is **not** an `rc-dock` matter. That's just how React works.

See also:
- https://stackoverflow.com/a/55248699
- https://medium.com/@rossbulat/how-to-use-react-refs-4541a7501663#0a2c
