### ISSUE TITLE
Squeezed tab infinitely renavigates tab panel header scroll

### ISSUE THREAD

**Issue by andrewsantarin** [ticlo/rc-dock#24]
Hi, @rinick.

I spotted a bug while testing a local instance of `rc-dock` on my mobile. See my recording:
https://youtu.be/LqtXzAVvTk8

When the panel has a given `panelExtra`, and you dock the tab header to a new panel such that there's not enough space to fit the tab header in that panel, the panel's tab header scroll loops forever. 

**Notes**
1. You need to drag & drop the tab using the tab header, not the whole panel's tab header bar, or else you can't reproduce this bug.
2. You should use a small viewport size to emulate it, such as an iPhone 5S/SE (real or emulated) or a really narrow layout using CSS. The bug won't happen if the layout is wide enough.

**Comment by rinick** [comment]
this might be a bug from rc-tabs package.  but even after solving this bug, you still end up with either unclickable tabs or unclickable extra content.

I think the real solution to this issue is to always give a minimal width to panel with extra content, right now min width only works on tabs,  I will add minWidth and minHeight to panelLock

**Comment by andrewsantarin** [comment]
Thanks for that heads-up, @rinick. Looks like I'll have to reproduce it and report it directly at `rc-tabs`...

**Comment by veeramarni** [comment]
@andrewsantarin  We found the same issue, did find solution for yours?

**Comment by rinick** [comment]
latest rc-tabs version has re-written that part, this issue should be gone once I pushed rc-dock 3.0 to npm
