### ISSUE TITLE
Feature requests: Hide, Enlarge, & Popup

### ISSUE THREAD

**Issue by DaxChen** [ticlo/rc-dock#25]
Hi @rinick,

First of all, thank you for the awesome work! This is indeed the best react based layout manager after days of searching. The cache mode is brilliant and solves a lot of the re-rendering problem!

Compared to some of the other libraries such as `golden-layout`, `react-mosaic`, `flexlayout-react`, there are still three features missing:

1. toggle hide: something like double click the tabs label to toggle hide the pane
2. enlarge: enlarge the pane to full screen
2. popup window: maybe something like https://github.com/rmariuzzo/react-new-window?

Do you plan to support these?

Thanks!

**Comment by rinick** [comment]
1) I have no plan to add this feature naively, but I think it won't be too hard to implement it on the top of rc-dock. 
2) Yes, it's probably the next major feature I will add, 
3) I'd be happy to support that as long as it doesn't require too much change on the current frame, I will need to do some research

**Comment by DaxChen** [comment]
May I ask why no plan to support hide?

**Comment by rinick** [comment]
> May I ask why no plan to support hide?

different people have different expectation of hidden panel's behavior. I can find a standard design for that feature.  adding that feature would actually make it harder for people to implement in the way he wants

**Comment by rinick** [comment]
@DaxChen maximize panel is implemented in v 2.4.0
I'm closing this ticket for now.

if you find popup window is an important feature to you, you can create a new ticket to track these issues one by one.

**Comment by andrewsantarin** [comment]
> 3. popup window: maybe something like https://github.com/rmariuzzo/react-new-window?

@DaxChen @rinick Pardon me. This is a long post, but only because my coworkers and I also have been trying to get this feature implemented (we need it). We wanted to emulate `golden-layout`'s ability in popping up a tab in a new window.

I've tried this myself over and over using `react-new-window` / `react-popup-component` as the popup manager in as many ways as I could think of (e.g. creating the new components from main, using a new app instance altogether, using routers to decide whether it's a brand new instance or just a child, state sync across tabs --- it's pretty messy). From my observations, I can tell you that taking the naive approach below won't work 100% correctly:

```jsx
<NewWindow>
  {/* Prints the layout as expected, but the drag events are still linked to the parent window. */}
  <DockLayout {...detachedDockLayoutProps} />
</NewWindow>
```

The reason being that drag events are set up from the parent window. Across the codebase, it consistently looks like this:

```
document.addEventListener()
document.removeEventListener()
```

This is okay if your app is expected to run on **one window only**. If you decide to run a polywindow environment, well... the handlers will register on the parent window instead of what you expect: the child window.

## Solution(?)
I think `rc-dock` needs to design its event listeners under the assumption that you could, say, assign a different document on the component when it mounts...

```tsx
let targetWindow: Window | null = null;
const handleOpen = (newWindow: Window) => {
  targetWindow = newWindow;
}

const doGetDocument = () => targetWindow.document;

<NewWindow
  onOpen={handleOpen}
>
  <DockLayout
    layout={layout}
    getDocument={doGetDocument} // Point the drag handlers to the new window's document node.
  />
</NewWindow>
```

In fact, this is how `ag-grid` solves the "rendering in the child window" problem. Check out [this link](https://www.ag-grid.com/javascript-grid-callbacks/) under **getDocument()**. Similar case applies to `rc-menu` on where it should render a dropdown menu: Check out [this link](https://github.com/react-component/menu#menu-props): **getPopupContainer**.

This should help point all the `addEventListener` and `removeEventListener` code to the document that they're supposed to listen in, not the parent that created them.

However...

## You Still Need To Make Design Considerations
From what I've tried, you should also think about how you manage new windows, because of a few reasons:

### Creating a new `about:blank` window (default behavior of `react-new-window`)
- You can't reload your child window. Ever. Go to https://golden-layout.com, detach one of the UI tabs in the example and try to reload it. [They seem to have an issue filed already, but no reply yet.](https://github.com/golden-layout/golden-layout/issues/534)
- You'll need to apply the same context as a prop to all of your components, or else their listeners & renderers might also work incorrectly.

### Creating a new `/child-tab/uuid=your-child-tab-uuid` subroute window
- You can circumvent the `about:blank` problem by just using a new app instance altogether, similar to how you open a tab and type your app URL in the address bar, with one exception: using a subroute. Your subroute will handle what to do with the detached tab (this one is heavily opinionated. You could use any routing library of your choice to achieve the same result).
- The hard part (to me) is, well... synchronizing data across all of those tabs, if all tabs need to be consistent. I don't even know where to start here. Some ways you could do this is by using `localStorage` to keep state or share the data using the `BroadcastChannel` API. My use case was quite complicated for `localStorage` because we could be transacting with `localStorage` hundreds of times per second, and `BroadcastChannel` is still not widespread...

------
Again, sorry, it's lengthy, but I'd like to at least contribute.

**Comment by rinick** [comment]
@andrewsantarin the way you use it is very differently from how I would implement it
I will probably use single Layout, and wrap NewWindow internally, treat it just like another type of float panel, so you can drag a panel from one window to the other (since they are in the same layout)

But that design also means you will only have one panel in each popup window. 
Could you let me know the reason why a popup window need another layout with multiple panels?

**Comment by andrewsantarin** [comment]
>Could you let me know the reason why a popup window need another layout with multiple panels?

@rinick: Project requirements.

It's more on the nice-to-have side, but the "gold standard" spec is that:

- we could have multiple windows, each containing its own `<DockLayout>`
  - if this isn't feasible, the least we intended to offer is, as you said, child windows with single layout components; the bare minimum
- tabs could be transferred between windows using drag and drop. (my best guess is this would be an Electron feature)
- there should be only one window running a socket connection to the API, which, in our case, is the main window, while the child windows would depend on the main for data.

Sorry for replying so late, I was occupied with other daily tasks.

**Comment by rinick** [comment]
@andrewsantarin @DaxChen @mlomb
3.0.0-alpha.2 now supports react-new-window, please check the new example
https://ticlo.github.io/rc-dock/examples/#new-window
