### ISSUE TITLE
Support RTL

### ISSUE THREAD

**Issue by kompaktkikare** [ticlo/rc-dock#26]
I would need RTL support:
https://material.io/design/usability/bidirectionality.html#mirroring-layout.
I am setting the dir="rtl" in html.
RC-Dock seems to support it somewhat, but when resizing a panel with the mouse (left/right) the panel goes in the other direction.
Some other issues:
* Close button is located to the right, should be left of the tab name
* The maximize button is located to the right

**Comment by rinick** [comment]
I think part of it can be done with some css change
first, the layout panels have to work in a left to right order, it's unrelated to reading order
you can give the layout element a ltr direction and only assign rtl to the content

but the issues with tab bar is different, I think it's from the rc-tabs package
https://github.com/react-component/tabs
that part is much harder to fix, since rc-tabs is part of the antd framework, I recommend you to  submit bug at 
https://github.com/ant-design/ant-design
