### ISSUE TITLE
tabs of different dock-panel also get render for any change in the tabs of other dock-panel

### ISSUE THREAD

**Issue by veeramarni** [ticlo/rc-dock#27]
Seems the `tabs` in a different `DockPanel` always render even the data on that `Tabs` had not changed. 

https://github.com/ticlo/rc-dock/blob/master/src/DockTabs.tsx#L190  <-- always leads to `true`

Seems like there is a nested `parent` object that was causing this issue. 

![image](https://user-images.githubusercontent.com/3382355/67634376-60d48e80-f891-11e9-861c-4f1184e28718.png)

**Comment by rinick** [comment]
nice catch, I will fix that

**Comment by rinick** [comment]
@veeramarni you are right, it always return true. But seems it doesn't cause too much performance issue. The re-render protection is already done by the parent component, that's why it always sees different tab data in shouldComponentUpdate
I will probably just remove that check and let it always return true.

Do you have see any other issue about that?
