### ISSUE TITLE
Undock panels to a new window

### ISSUE THREAD

**Issue by mlomb** [ticlo/rc-dock#33]
Using React portals is possible to achieve docking functionality with multiple windows.
Codepen: https://codepen.io/davidgilbertson/pen/xPVMqp
Article: https://medium.com/hackernoon/using-a-react-16-portal-to-do-something-cool-2a2d627b0202

This may be very difficult -or impossible- to implement and I don't expect it soon. With this it may be possible to achieve full desktop docking features in the browser.

It has other quirks like the styles have to be copied over the created window.

Thoughts on the idea?

**Comment by mlomb** [comment]
Duplicate of #25

**Comment by rinick** [comment]
Let's reopen this issue, since #25 has several different topics

**Comment by rinick** [comment]
drag to directly create new browser window might never be a feature in rc-dock.  but you can use your own code to create new window and put a DockLayout there. it should already work.

right now the issue is dragging between 2 different DockLayouts.
Current version disable that behavior by default, even when it was possible in previous version, there are still several issues that make it unusable.
