### ISSUE TITLE
Question - roadmap/future of RC dock

### ISSUE THREAD

**Issue by johnjesse** [ticlo/rc-dock#44]
@rinick 

Hi, we're looking at using RC dock in our codebase and was wondering what the roadmap is for RC dock in the future. I saw that an alpha version for 3.0... was released a few days ago, so I was wondering if you're planning on doing a major version bump and what changes would include.

RC is pretty cool 😄  Thanks for making and sharing it

**Comment by rinick** [comment]
so for the late reply.
There is no plan of making any breaking changes. 

In the future when the main ticlo project is close to release, there might be some change on how the tabs are handled when there are too many of them. I might add a new option instead of changing the default behavior, so existing project will stay the same.

**Comment by johnjesse** [comment]
Cool thanks for the info
