### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by jeremy-coleman** [ticlo/rc-dock#45]
Any advice on how to implement this?

![image](https://user-images.githubusercontent.com/25135855/85950418-8dfaa480-b92a-11ea-8f76-474c7deb65f5.png)

**Comment by rinick** [comment]
you mean making it work like a grid instead of layers of horizontal/vertical layout?

you can use raw Divider instead of DividerBox. so in the callback you can sync the layout of every sibling group.
please check how DividerBox is implemented itself
https://github.com/ticlo/rc-dock/blob/master/src/DividerBox.tsx
