### ISSUE TITLE
Preventing components from re-mounting

### ISSUE THREAD

**Issue by zofbanach** [ticlo/rc-dock#54]
Hi everyone,
First, I wanted to say that I'm using this component and I'm really happy with it, it works great!

The only thing I have noticed is that every time a tab is moved or maximized (or minimized), the component that is in the content of it is unmounted and mounted again. Is there a way to prevent this behavior? I would prefer not to lose the state of component every time it is being dragged.
I'm using defaultLayout.

**Comment by rinick** [comment]
because the layout moves tabs around, also adds/removes  Horizontal Vertical layout in the middle, it has to be unmounted in many cases 
have you tried cached=true for the tab, when that's set to true it cache the tab content with react portal so the state can be preserved 
https://ticlo.github.io/rc-dock/examples/#tab-cache

**Comment by zofbanach** [comment]
@rinick Thanks! That solves my problem :) 
It works great now, but for the future (if more data was stored in components state), have you experienced any performance issues using this solution?

**Comment by rinick** [comment]
@zofbanach no I don't think there will be any performance issue.
