### ISSUE TITLE
Minimize of the panels

### ISSUE THREAD

**Issue by pe7r** [ticlo/rc-dock#77]
I want to be able to minimize the panel on the side like, for example - two panels are opened near each other, and when I click on minimize action of one panel - it hides the panel on the side (e.g. close), but the name of the tabs is still visible on the side  where it was hidden so I could click on a closed panel to show make it visible again.

**Comment by rinick** [comment]
you can simply just make a vertical tab bar on the left, and show all the tabs that are removed from layout. and add them back to layout when clicked.

I don't see this feature become a generic api in rc-dock, because people will have very different requirement, and there is no single implementation that can satisfy everyone

**Comment by Avi-Levi** [comment]
@rinick 
is it possible to add e.g. buttons to the panel's title row?

**Comment by rinick** [comment]
> @rinick
> is it possible to add e.g. buttons to the panel's title row?

yes, you can use panelExtra to add button for the whole panel
or you can just add button for each tab in tab's title area
