### ISSUE TITLE
Auto-highlighting of another content in Safari and Edge browsers during drag-n-drop and resize events; expanded functionality of rearranging tabs

### ISSUE THREAD

**Issue by Likurg2010** [ticlo/rc-dock#8]
Good morning. Recently, i have noticed a little bit strange behavior in Safari and Edge browsers. When you use "drag-n-drop" and "resize" events in that browsers, you can see, that content behind cursor starting to be highlighted.
And another question: is it possible to rearrange tabs between themselves when tabLocked property is true, in some way? I need panelData with some tabs, which i could rearrange, but disallow splitting for them and moving out from their parent container to another ones. Thanks.

**Comment by rinick** [comment]
Edge and Safari's issue is fixed in 2.3.1,  

to achieve the other feature , you can add a group with `tabLocked:true` 
https://ticlo.github.io/rc-dock/interfaces/tabgroup.html#tablocked

to understand how group works you can check the panel style example
https://ticlo.github.io/rc-dock/examples/#panel-style

**Comment by Likurg2010** [comment]
Cool! Thanks a lot)
